#!/bin/sh

set -o pipefail -o errexit -o nounset

cd "$(dirname "$0")/.."


device=/dev/ttyACM*
if [ $device = "/dev/ttyACM*" ]; then
  device=/dev/ttyUSB*
fi

echo $device

arduino-cli monitor \
  -p $device -c 115200
